spring:
  datasource:
    url: jdbc:mysql://localhost:3308/snstest?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
